ifndef ROLLCOMPILER
  ROLLCOMPILER = gnu
endif
COMPILERNAME := $(firstword $(subst /, ,$(ROLLCOMPILER)))

ifndef ROLLMPI
  ROLLMPI = rocks-openmpi
endif
MPINAME := $(firstword $(subst /, ,$(ROLLMPI)))

NAME           = sdsc-octave
VERSION        = 5.2.0
RELEASE        = 0
PKGROOT        = /opt/octave

SRC_SUBDIR     = octave

SOURCE_NAME    = octave
SOURCE_SUFFIX  = tar.gz
SOURCE_VERSION = $(VERSION)
SOURCE_PKG     = $(SOURCE_NAME)-$(SOURCE_VERSION).$(SOURCE_SUFFIX)
SOURCE_DIR     = $(SOURCE_PKG:%.$(SOURCE_SUFFIX)=%)


PARALLEL_NAME    = parallel
PARALLEL_SUFFIX  = tar.gz
PARALLEL_VERSION = 3.1.3
PARALLEL_PKG     = $(PARALLEL_NAME)-$(PARALLEL_VERSION)-Octave-5.1.0-patch.$(PARALLEL_SUFFIX)
PARALLEL_DIR     = $(PARALLEL_NAME)-$(PARALLEL_VERSION)

STRUCT_NAME    = struct
STRUCT_SUFFIX  = tar.gz
STRUCT_VERSION = 1.0.16
STRUCT_PKG     = $(STRUCT_NAME)-$(STRUCT_VERSION).$(STRUCT_SUFFIX)
STRUCT_DIR     = $(STRUCT_PKG:%.$(STRUCT_SUFFIX)=%)

SIGNAL_NAME    = signal
SIGNAL_SUFFIX  = tar.gz
SIGNAL_VERSION = 1.4.1
SIGNAL_PKG     = $(SIGNAL_NAME)-$(SIGNAL_VERSION).$(SIGNAL_SUFFIX)
SIGNAL_DIR     = $(SIGNAL_PKG:%.$(SIGNAL_SUFFIX)=%)

CONTROL_NAME    = control
CONTROL_SUFFIX  = tar.gz
CONTROL_VERSION = 3.2.0
CONTROL_PKG     = $(CONTROL_NAME)-$(CONTROL_VERSION).$(CONTROL_SUFFIX)
CONTROL_DIR     = $(CONTROL_PKG:%.$(CONTROL_SUFFIX)=%)

TAR_GZ_PKGS    = $(SOURCE_PKG) $(STRUCT_PKG) $(PARALLEL_PKG) $(CONTROL_PKG) $(SIGNAL_PKG)

RPM.EXTRAS     = AutoReq:No\nAutoProv:No
RPM.PREFIX     = $(PKGROOT)
